sonata_admin:
    title: 'Ticket Management'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    templates:
        user_block:     '@SonataAdmin/Core/user_block.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
